# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Leo
email: aleo1337@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Engineer by Day, Nerd by Night</h3><h1>Alex Leo</h1><h3>Software Engineer, Hack Reactor Student, Gamer, Rambler, and Tea Drinker</h3>Personal Insights Gained Through Technological Discovery"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aleo23.github.io" # the base hostname & protocol for your site
twitter_username: PrawdigeeAL
github_username:  ALeo23

# Build settings
markdown: kramdown
